<?php

use Illuminate\Database\Seeder;

class SeedingTypesTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('types')->insert(
            [
                [
                    'name' => 'output_document',
                    'alias' => 'Вихідні',
                    'native_name' => 'ЖУРНАЛ \n реєстрації вихідних документів',
                    'num' => 'Індекс документа',
                    'date' => 'Дата',
                    'author' => null,
                    'header' => 'Найменування або короткий зміст документа',
                    'key_words' => null,
                    'description' => 'Примітки',
                    'number_of_copies' => 'Кількість примірників',
                    'number_of_pages' => 'Кількість аркушів',
                    'description_copy' => 'Номери примірників',
                    'number_of_appendix' => null,
                    'number_of_pages_appendix' => null,
                    'case_number' => 'Номер справи',
                    'page_in_case' => 'номери аркушів',
                    'relation_document' => null,
                    'outside_num' => 'Вхідний номер виконаного документа',
                    'outside_date' => null,
                    'correspondent' => 'Кому надіслано документ',
                    'return_date' => null,
                ],

                [
                    'name' => 'command_directive',
                    'alias' => 'Накази',
                    'native_name' => 'КНИГА \n обліку наказів і директив',
                    'num' => 'Порядкові номери наказів і директив',
                    'date' => 'Дата підписання',
                    'author' => 'Хто підписав чи звідки одержано документ. Номер і дата супроводного листа',
                    'header' => 'Назва наказу (директиви)',
                    'key_words' => null,
                    'description' => null,
                    'number_of_copies' => 'Кількість примірників',
                    'number_of_pages' => null,
                    'description_copy' => 'Номери примірників',
                    'number_of_appendix' => null,
                    'number_of_pages_appendix' => null,
                    'case_number' => 'Номер справи, до якої підшито документ',
                    'page_in_case' => 'сторинка',
                    'relation_document' => null,
                    'outside_num' => 'Номер супроводного листа',
                    'outside_date' => 'Дата супроводного листа',
                    'correspondent' => 'Кому',
                    'return_date' => null,
                ],

                [
                    'name' => 'declaration_directive',
                    'alias' => 'Доведення',
                    'native_name' => 'ЖУРНАЛ \n оголошення наказів, директив та інших \n службових документів особовому складу',
                    'num' => 'Номер службового документа',
                    'date' => 'Дата службового документа',
                    'author' => null,
                    'header' => 'Заголовок службового документа',
                    'key_words' => null,
                    'description' => 'Кому оголошено (до кого доведено) службовий документ і дата',
                    'number_of_copies' => null,
                    'number_of_pages' => null,
                    'description_copy' => null,
                    'number_of_appendix' => null,
                    'number_of_pages_appendix' => null,
                    'case_number' => null,
                    'page_in_case' => null,
                    'relation_document' => null,
                    'outside_num' => null,
                    'outside_date' => 'Дата надходження службового документа до військової частини',
                    'correspondent' => null,
                    'return_date' => null,
                ],

                [
                    'name' => 'register_confidential_doc',
                    'alias' => 'Реєстрація ДСК',
                    'native_name' => 'ЖУРНАЛ \n реєстрації документів з гриформ "Для службового користування"',
                    'num' => 'Індекс документа',
                    'date' => 'Дата надходження документа',
                    'author' => null,
                    'header' => 'Назва виду документа та коротикий зміст',
                    'key_words' => null,
                    'description' => 'Примітка',
                    'number_of_copies' => 'Кількість аркушів документа',
                    'number_of_pages' => 'Кількість аркушів додатка',
                    'description_copy' => 'Кількість та номери примірників',
                    'number_of_appendix' => null,
                    'number_of_pages_appendix' => null,
                    'case_number' => 'Індекс (номер) справи, до якої підшито документ',
                    'page_in_case' => null,
                    'relation_document' => null,
                    'outside_num' => 'Індекс вхідного документа',
                    'outside_date' => 'Дата вхідного документа',
                    'correspondent' => 'Звідки надійшов або кому адресований',
                    'return_date' => null,
                ],

                [
                    'name' => 'input_doc',
                    'alias' => 'Вхідні',
                    'native_name' => 'ЖУРНАЛ \n реєстрації вхідних документів',
                    'num' => 'Індекс документа',
                    'date' => 'Дата надходження документа',
                    'author' => null,
                    'header' => 'Короткий зміст',
                    'key_words' => null,
                    'description' => 'Відмітка про отрімання документа',
                    'number_of_copies' => null,
                    'number_of_pages' => null,
                    'description_copy' => null,
                    'number_of_appendix' => null,
                    'number_of_pages_appendix' => null,
                    'case_number' => null,
                    'page_in_case' => null,
                    'relation_document' => null,
                    'outside_num' => 'Індекс одержаного документа',
                    'outside_date' => 'Дата одержаного документа',
                    'correspondent' => 'Кореспондент',
                    'return_date' => null,
                ],

                [
                    'name' => 'register_copybook',
                    'alias' => 'Зошити',
                    'native_name' => 'КНИГА \n обліку робочих зошитів',
                    'num' => 'Номер за порядком',
                    'date' => null,
                    'author' => 'Призвище та ініціали виконавця',
                    'header' => 'Найменування',
                    'key_words' => null,
                    'description' => null,
                    'number_of_copies' => null,
                    'number_of_pages' => 'Кількість аркушів',
                    'description_copy' => null,
                    'number_of_appendix' => null,
                    'number_of_pages_appendix' => null,
                    'case_number' => null,
                    'page_in_case' => null,
                    'relation_document' => null,
                    'outside_num' => null,
                    'outside_date' => 'Дата отримання',
                    'correspondent' => null,
                    'return_date' => 'Дата зворонього прийому',
                ],

                [
                    'name' => 'register_disk',
                    'alias' => 'Диски',
                    'native_name' => 'ЖУРНАЛ \n обліку електронних носіїв інформації',
                    'num' => 'Обліковий номер носія',
                    'date' => 'Дата взяття на облік',
                    'author' => 'Призвище та ініціали виконавця',
                    'header' => 'Вид електронного носія',
                    'key_words' => null,
                    'description' => 'Примітка',
                    'number_of_copies' => null,
                    'number_of_pages' => null,
                    'description_copy' => null,
                    'number_of_appendix' => null,
                    'number_of_pages_appendix' => null,
                    'case_number' => null,
                    'page_in_case' => null,
                    'relation_document' => null,
                    'outside_num' => null,
                    'outside_date' => 'Дата видачи носія виконавцю',
                    'correspondent' => 'Найменування структурного підрозділу',
                    'return_date' => 'Дата зворонього прийому',
                ],
            ]
        );
    }
}
