<?php

use Illuminate\Database\Seeder;

class SeedingTableOrderColumns extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('order_columns')->insert(
            [
                [
                    'type_name' => 'output_document',
                    'num' => 0,
                    'date' => 1,
                    'author' => null,
                    'header' => 2,
                    'key_words' => null,
                    'description' => 10,
                    'number_of_copies' => 5,
                    'number_of_pages' => 7,
                    'description_copy' => 6,
                    'number_of_appendix' => null,
                    'number_of_pages_appendix' => null,
                    'case_number' => 8,
                    'page_in_case' => 9,
                    'relation_document' => null,
                    'outside_num' => 3,
                    'outside_date' => null,
                    'correspondent' => 4,
                    'return_date' => null,
                ],

                [
                    'type_name' => 'command_directive',
                    'num' => 0,
                    'date' => 1,
                    'author' => 2,
                    'header' => 3,
                    'key_words' => null,
                    'description' => null,
                    'number_of_copies' => 4,
                    'number_of_pages' => null,
                    'description_copy' => 8,
                    'number_of_appendix' => null,
                    'number_of_pages_appendix' => null,
                    'case_number' => 9,
                    'page_in_case' => 10,
                    'relation_document' => null,
                    'outside_num' => 6,
                    'outside_date' => 7,
                    'correspondent' => 5,
                    'return_date' => null,
                ],

                [
                    'type_name' => 'declaration_directive',
                    'num' => 0,
                    'date' => 1,
                    'author' => null,
                    'header' => 3,
                    'key_words' => null,
                    'description' => 4,
                    'number_of_copies' => null,
                    'number_of_pages' => null,
                    'description_copy' => null,
                    'number_of_appendix' => null,
                    'number_of_pages_appendix' => null,
                    'case_number' => null,
                    'page_in_case' => null,
                    'relation_document' => null,
                    'outside_num' => null,
                    'outside_date' => 2,
                    'correspondent' => null,
                    'return_date' => null,
                ],

                [
                    'type_name' => 'register_confidential_doc',
                    'num' => 1,
                    'date' => 0,
                    'author' => null,
                    'header' => 5,
                    'key_words' => null,
                    'description' => 10,
                    'number_of_copies' => 6,
                    'number_of_pages' => 7,
                    'description_copy' => 8,
                    'number_of_appendix' => null,
                    'number_of_pages_appendix' => null,
                    'case_number' => 9,
                    'page_in_case' => null,
                    'relation_document' => null,
                    'outside_num' => 3,
                    'outside_date' => 2,
                    'correspondent' => 4,
                    'return_date' => null,
                ],

                [
                    'type_name' => 'input_doc',
                    'num' => 1,
                    'date' => 0,
                    'author' => null,
                    'header' => 5,
                    'key_words' => null,
                    'description' => 6,
                    'number_of_copies' => null,
                    'number_of_pages' => null,
                    'description_copy' => null,
                    'number_of_appendix' => null,
                    'number_of_pages_appendix' => null,
                    'case_number' => null,
                    'page_in_case' => null,
                    'relation_document' => null,
                    'outside_num' => 4,
                    'outside_date' => 3,
                    'correspondent' => 2,
                    'return_date' => null,
                ],

                [
                    'type_name' => 'register_copybook',
                    'num' => 0,
                    'date' => null,
                    'author' => 2,
                    'header' => 1,
                    'key_words' => null,
                    'description' => null,
                    'number_of_copies' => null,
                    'number_of_pages' => 3,
                    'description_copy' => null,
                    'number_of_appendix' => null,
                    'number_of_pages_appendix' => null,
                    'case_number' => null,
                    'page_in_case' => null,
                    'relation_document' => null,
                    'outside_num' => null,
                    'outside_date' => 4,
                    'correspondent' => null,
                    'return_date' => 5,
                ],

                [
                    'type_name' => 'register_disk',
                    'num' => 0,
                    'date' => 1,
                    'author' => 4,
                    'header' => 2,
                    'key_words' => null,
                    'description' => 7,
                    'number_of_copies' => null,
                    'number_of_pages' => null,
                    'description_copy' => null,
                    'number_of_appendix' => null,
                    'number_of_pages_appendix' => null,
                    'case_number' => null,
                    'page_in_case' => null,
                    'relation_document' => null,
                    'outside_num' => null,
                    'outside_date' => 5,
                    'correspondent' => 3,
                    'return_date' => 6,
                ],
            ]
        );
    }
}
